nwa:
  # basic
  cmd: "add"                        # Default: "add"; Can be overwritten by --command (-c) flag; Optional: "add", "check", "remove", "update"
  holder: "MSD-RS Project LiJia"    # Default: "<COPYRIGHT HOLDER>"
  year: "2026"                      # Default: Current Year
  license: "BSD-2-Clause"          # Default: "apache"
  spdxids: "BSD-2-Clause"          # Default: ""
  skip:                             # Default: []
    - ".venv/**"
  path:                             # Default: []
    - "src/**/*.rs"
    - "python/**/*.py"
  # advanced
  mute: false                       # Default: false (unspecified)
  verbose: false                    # Default: false (unspecified)
  fuzzy: false                      # Default: false (unspecified); Used for "check" and "remove" commands
  tmpltype: ""                      # Default: ""; Optional: "live", "static", "raw"
  tmpl: ""                          # Default: ""                                                       
  keyword: []                       # Default: []; Used for "add" and "update" commands
  style: []   